services:
   catalogdb:
        container_name: catalogdb
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=Chamara@1993
          - POSTGRES_DB=CatalogDb
        restart: always
        ports:
            - "5433:5432"
        volumes:
          - postgres_catalog:/var/lib/postgresql/data/ 
         